# Generated by Django 5.1.4 on 2025-01-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='video.face')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='user_profile.profile')),
            ],
        ),
    ]
