# Generated by Django 5.1.4 on 2025-01-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('video', '0002_alter_face_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceprofile',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_profiles', to='video.face'),
        ),
        migrations.AlterUniqueTogether(
            name='faceprofile',
            unique_together={('profile', 'face')},
        ),
    ]
