# Generated by Django 5.1.4 on 2025-01-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_faces', to='user_profile.profile'),
        ),
    ]
