# Generated by Django 5.1.4 on 2025-01-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
    ]
