# Generated by Django 5.1.4 on 2025-01-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_face_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
