# Generated by Django 5.1.4 on 2025-01-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_faceprofile_profile'),
        ('video', '0004_remove_face_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_faces', to='user_profile.profile'),
        ),
    ]
