# Generated by Django 5.1.4 on 2025-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_face_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='face/'),
        ),
    ]
