# Generated by Django 5.1.4 on 2025-01-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='video.video'),
        ),
    ]
